name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Start Local Server
        run: npm start &

      - name: Wait for Server to Start
        run: sleep 10

      - name: Run E2E Tests with Cypress
        run: npm run test:e2e